//
//  TestViewModel.swift
//  SushiTime
//
//  Created by 1 on 22.11.17.
//  Copyright © 2017 Self. All rights reserved.
//

import Foundation

struct RollsViewModel: OrderDetailProvider {
    var itemsToDisplay: [OrderDetailItem]  = [OrderDetailItem(name: "Філадельфія з свіжою полуницею", imageName: "FiladelphiaWithFresh Strawberries", priceImage: "CashImage", priceName: 120, weightImage: "WeightImage", weightName: 190, aboutName: "• Лосось\n• Вершковий сир\n• Полуниця свіжа\n• 8шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Сирний рол", imageName: "cheeseRoll", priceImage: "CashImage", priceName: 64, weightImage: "WeightImage", weightName: 190, aboutName: "•Вершковий сир \n• Сир тофу\n• Кунжут\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Каліфорнія з сурімі", imageName: "KaliforniaSurimi", priceImage: "CashImage", priceName: 68, weightImage: "WeightImage", weightName: 190, aboutName: "•Вершковий сир Кунжут\n• Огірок\n• Cурімі\n• 8 шт. ", grLabel: "гр."),
                                              OrderDetailItem(name: "Вегетеріанський", imageName: "Vegetarian", priceImage: "CashImage", priceName: 72, weightImage: "WeightImage", weightName: 205, aboutName: "• Авокадо \n• Кунжут\n• Огірок\n• Чука\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Тамаго Сяке", imageName: "TamagoSyake", priceImage: "CashImage", priceName: 78, weightImage: "WeightImage", weightName: 190, aboutName: "• Омлет Тамаго \n• Лосось\n• Кунжут\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Чікен хот", imageName: "ChickenHot", priceImage: "CashImage", priceName: 92, weightImage: "WeightImage", weightName: 190, aboutName: "• Кляр темпура\n• Копчена курка\n• Вершковий сир\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Футомакі", imageName: "Futomaki", priceImage: "CashImage", priceName: 88, weightImage: "WeightImage", weightName: 240, aboutName: "• Сурімі\n• Ікра масаго\n• Авокадо\n• Огірок\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Чікен чіз", imageName: "ChikenCheese", priceImage: "CashImage", priceName: 84, weightImage: "WeightImage", weightName: 210, aboutName: "• Вершковий сир\n• Зелена цибуля\n• Копчена курка\n• Тостовий сир\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Каліфорнія", imageName: "California", priceImage: "CashImage", priceName: 92, weightImage: "WeightImage", weightName: 210, aboutName: "• Сурімі\n• Ікра масаго\n• Авокадо\n• Огірок\n• 6 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Філадельфія чіз", imageName: "FiladelfiaCheese", priceImage: "CashImage", priceName: 98, weightImage: "WeightImage", weightName: 190, aboutName: "• Вершковий сир\n• Сир тофу\n• Лосось\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Рол Якудза", imageName: "Yakudza", priceImage: "CashImage", priceName: 99, weightImage: "WeightImage", weightName: 210, aboutName: "• Вершковий сир\n• Стружка тунця\n• Лосось\n• Яблуко\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Футомакі з лососем та авокадо", imageName: "FutomakiWithLososAndAvokado", priceImage: "CashImage", priceName: 99, weightImage: "WeightImage", weightName: 215, aboutName: "• Авокадо\n• Лосось\n• 10 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Гарячий рол з вугрем", imageName: "HotRollWithVuhor", priceImage: "CashImage", priceName: 135, weightImage: "WeightImage", weightName: 190, aboutName: "• Кляр темпура\n• Вугор\n• Вершковий сир\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Пивний рол", imageName: "BeerRoll", priceImage: "CashImage", priceName: 110, weightImage: "WeightImage", weightName: 210, aboutName: "• Масляна риба\n• Вершковий сир\n• Зелена цибуля\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Кунсей", imageName: "Kunsey", priceImage: "CashImage", priceName: 130, weightImage: "WeightImage", weightName: 195, aboutName: "• Кунжут (чорний)\n• Зелена цибуля\n• Соус спайс\n• Лосось\n• Вугор\n• 8шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Філадельфія грін", imageName: "FiladelfiaGreen", priceImage: "CashImage", priceName: 109, weightImage: "WeightImage", weightName: 220, aboutName: "• Вершковий сир\n• Авокадо\n• Лосось\n• Огірок\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Філадельфія", imageName: "Filadelfia", priceImage: "CashImage", priceName: 109, weightImage: "WeightImage", weightName: 190, aboutName: "• Вершковий сир\n• Авокадо\n• Лосось", grLabel: "гр."),
                                              OrderDetailItem(name: "Чорний самурай", imageName: "BlackSamuray", priceImage: "CashImage", priceName: 129, weightImage: "WeightImage", weightName: 200, aboutName: "• Копчений вугор\n• Вершковий сир\n• Омлет Тамаго\n• Чорний кунжут", grLabel: "гр."),
                                              OrderDetailItem(name: "Філадельфія вакаме", imageName: "FiladelfiaVakame", priceImage: "CashImage", priceName: 125, weightImage: "WeightImage", weightName: 220, aboutName: "• Вершковий сир\n• Чука вакаме\n• Авокадо\n• Лосось\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Філадельфія чіз з вугрем", imageName: "FiladelfiaCheeseWithVuhor", priceImage: "CashImage", priceName: 145, weightImage: "WeightImage", weightName: 190, aboutName: "• Копчений вугор\n• Cир вершковий\n• Сир тофу\n• Соус унагі", grLabel: "гр."),
                                              OrderDetailItem(name: "Каліфорнія фреш", imageName: "KaliforniaFresh", priceImage: "CashImage", priceName: 119, weightImage: "WeightImage", weightName: 210, aboutName: "• Ікра масаго\n• Авокадо\n• Лосось\n• Огірок\n• 6 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Філадельфія з тунцем", imageName: "FiladelfiaWithTunez", priceImage: "CashImage", priceName: 119, weightImage: "WeightImage", weightName: 190, aboutName: "• Вершковий сир\n• Авокадо\n• Тунець", grLabel: "гр."),
                                              OrderDetailItem(name: "Каліфорнія з вершковим сиром", imageName: "KaliforniaWithVershkovyCheese", priceImage: "HoCashImageme", priceName: 129, weightImage: "WeightImage", weightName: 220, aboutName: "• Вершковий сир\n• Кунжут\n• Авокадо\n• Лосось\n• Огірок\n• 8 шт.", grLabel: "гр."),
                                               OrderDetailItem(name: "Боніто", imageName: "Bonito", priceImage: "CashImage", priceName: 130, weightImage: "WeightImage", weightName: 210, aboutName: "• Вершковий сир\n• Стружка тунця\n• Тунець\n• Огірок\n• 8 шт.", grLabel: "гр."),
                                               //here weigth ? proshutto
                                              OrderDetailItem(name: "Прошутто Крудо", imageName: "ProshuttoKudo", priceImage: "HomCashImagee", priceName: 99, weightImage: "WeightImage", weightName: 190, aboutName: "• Прошутто Крудо\n• Вершковий сир\n• Зелена цибуля\n• Огірок", grLabel: "гр."),
                                              OrderDetailItem(name: "Золотий дракон", imageName: "GoldDragon", priceImage: "CashImage", priceName: 155, weightImage: "WeightImage", weightName: 210, aboutName: "• Копчений вугор\n• Вершковий сир\n• Ікра масаго\n• Соус унагі\n• Огірок\n• 8 шт.", grLabel: "гр."),
                                              OrderDetailItem(name: "Фірмовий рол Сяке Кадо", imageName: "FirmovyiRollSyakeKado", priceImage: "CashImage", priceName: 180, weightImage: "WeightImage", weightName: 220, aboutName: "•Копчений вугор\n• Вершковий сир\n• Лосось\n• 6 шт.\n• \n• ", grLabel: "гр."),
                                              OrderDetailItem(name: "Філадельфія з вугрем", imageName: "FiladelfiaWithVuhor", priceImage: "CashImageome", priceName: 155, weightImage: "WeightImage", weightName: 210, aboutName: "Копчений вугор• Вершковий сир\n• Авокадо\n• 8 шт.", grLabel: "гр.")]
}
